### ISSUE TITLE
Class 'Illuminate\Support\Collection' not found

### ISSUE THREAD

**Issue by Levdbas** [digitaldreams/googleplace#2]
Hi and thank you for this code! I am currently using this in a WordPress project and ran into two issues. I will make to seperate issues to cover this. This one is fairly straightforward.

```php
Class 'Illuminate\Support\Collection' not found
```

I fixed this by manually requiring `illuminate/collections` but it would be nice if this library included it in the composer dependencies as well for people not running Laravel.

**Comment by digitaldreams** [comment]
Thanks. I will do it

**Comment by apartamenti** [comment]
I am getting same error. Class "Illuminate\Support\Collection" not found. 

`composer require illuminate/collections` this code will fix error!
